spring:
  application:
    name: service-one
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:file:C:/h2data/sample;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
